/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <unistd.h>
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <pthread.h>
#include <errno.h>
#include <cstring>
#include <android/log.h>

/* Header for class com_jianjin33_ffmpeg_Request */

#ifndef _Included_com_jianjin33_ffmpeg_Request
#define _Included_com_jianjin33_ffmpeg_Request
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jianjin33_ffmpeg_Request
 * Method:    requestTest
 * Signature: ()Ljava/lang/String;
 */
#define TAG "Native_request"
#define LOG_D(...) __android_log_print(ANDROID_LOG_DEBUG,TAG ,__VA_ARGS__)

JNIEXPORT jstring JNICALL Java_com_jianjin33_ffmpeg_Request_requestTest
        (JNIEnv *, jobject);

static int32_t onInputEvent(struct android_app *app) {
    int sockClient = socket(AF_INET, SOCK_STREAM, 0);

    sockaddr_in sockAddr = {0};
    sockAddr.sin_family = AF_INET;
    sockAddr.sin_addr.s_addr = inet_addr("https://www.pecoo.com");
    sockAddr.sin_port = htonl(80);
    int nRet = connect(sockClient, reinterpret_cast<const sockaddr *>(&sockAddr),
                       sizeof(sockaddr_in));

    char szMsg[1024] = "haha";
    nRet = send(sockClient, szMsg, strlen(szMsg), 0);

}


#ifdef __cplusplus
}
#endif
#endif
